CREATE TABLE IF NOT EXISTS beers (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    brewery VARCHAR(255) NOT NULL,
    style VARCHAR(100) NOT NULL,
    abv DECIMAL(4,2) NOT NULL,
    rating DECIMAL(3,1),
    image_url TEXT,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
); 