CREATE TABLE IF NOT EXISTS beers (
    id SERIAL PRIMARY KEY,
    brewery_id INTEGER NOT NULL DEFAULT 0,
    name VARCHAR(255) NOT NULL DEFAULT '',
    cat_id INTEGER NOT NULL DEFAULT 0,
    style_id INTEGER NOT NULL DEFAULT 0,
    abv FLOAT NOT NULL DEFAULT 0,
    ibu FLOAT NOT NULL DEFAULT 0,
    srm FLOAT NOT NULL DEFAULT 0,
    upc INTEGER NOT NULL DEFAULT 0,
    filepath VARCHAR(255) NOT NULL DEFAULT '',
    descript TEXT NOT NULL,
    add_user INTEGER NOT NULL DEFAULT 0,
    last_mod TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
); 